import { useEffect, useState } from "react";
import { Download, AlertTriangle, Info } from "lucide-react";
import { Button } from "@/components/ui/button";

interface PdfManifest {
  version: string;
  contentHash: string;
  generatedAt: string;
  lastUpdated: string;
  sizeBytes: number;
  sourceSections?: number;
  pdfPath: string;
}

interface HandbuchPdfDownloadProps {
  /** Primary PDF URL (e.g. /downloads/handbuch-boxautomat.pdf) */
  primaryUrl: string;
  /**
   * Optional fallback URL. Defaults to `<primary>.last-good.pdf` derived from
   * the primary path (e.g. handbuch-boxautomat.last-good.pdf).
   */
  fallbackUrl?: string;
  /**
   * Optional manifest URL. Defaults to `<primary>.manifest.json` (written by
   * the build script). Used to display version + last-generated info.
   */
  manifestUrl?: string;
  /** Suggested filename for the download attribute. */
  fileName?: string;
  ariaLabel?: string;
  children?: React.ReactNode;
}

const deriveFallback = (url: string) =>
  url.replace(/\.pdf(\?.*)?$/i, ".last-good.pdf$1");

const deriveManifest = (url: string) =>
  url.replace(/\.pdf(\?.*)?$/i, ".manifest.json$1");

const formatDate = (iso: string) => {
  try {
    return new Date(iso).toLocaleString("de-DE", {
      dateStyle: "long",
      timeStyle: "short",
    });
  } catch {
    return iso;
  }
};

const formatSize = (bytes: number) => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
};

/**
 * Download button that probes the primary PDF on mount. If the request fails
 * (404, network error, or empty response), it transparently switches to the
 * last-known-good snapshot generated by the build script. Also shows the
 * version and generation timestamp from the manifest.
 */
const HandbuchPdfDownload = ({
  primaryUrl,
  fallbackUrl,
  manifestUrl,
  fileName,
  ariaLabel,
  children,
}: HandbuchPdfDownloadProps) => {
  const fallback = fallbackUrl ?? deriveFallback(primaryUrl);
  const manifest = manifestUrl ?? deriveManifest(primaryUrl);
  const [resolvedUrl, setResolvedUrl] = useState(primaryUrl);
  const [usingFallback, setUsingFallback] = useState(false);
  const [unavailable, setUnavailable] = useState(false);
  const [info, setInfo] = useState<PdfManifest | null>(null);

  useEffect(() => {
    let cancelled = false;

    const probe = async (url: string) => {
      try {
        const res = await fetch(url, { method: "HEAD", cache: "no-store" });
        if (!res.ok) return false;
        const len = res.headers.get("content-length");
        if (len !== null && Number(len) === 0) return false;
        return true;
      } catch {
        return false;
      }
    };

    const loadManifest = async () => {
      try {
        const res = await fetch(manifest, { cache: "no-store" });
        if (!res.ok) return;
        const data = (await res.json()) as PdfManifest;
        if (!cancelled) setInfo(data);
      } catch {
        /* manifest is optional */
      }
    };

    (async () => {
      if (await probe(primaryUrl)) {
        if (!cancelled) {
          setResolvedUrl(primaryUrl);
          setUsingFallback(false);
        }
      } else if (await probe(fallback)) {
        if (!cancelled) {
          setResolvedUrl(fallback);
          setUsingFallback(true);
        }
      } else if (!cancelled) {
        setUnavailable(true);
      }
      await loadManifest();
    })();

    return () => {
      cancelled = true;
    };
  }, [primaryUrl, fallback, manifest]);

  if (unavailable) {
    return (
      <div
        role="alert"
        className="inline-flex items-center gap-2 rounded-md border border-destructive/40 bg-destructive/10 px-4 py-2 text-sm text-destructive"
      >
        <AlertTriangle className="h-4 w-4" />
        PDF aktuell nicht verfügbar – bitte später erneut versuchen.
      </div>
    );
  }

  return (
    <div className="flex flex-col items-start gap-2">
      <Button asChild size="lg" className="gap-2">
        <a href={resolvedUrl} download={fileName} aria-label={ariaLabel}>
          <Download className="h-5 w-5" />
          {children ?? "Handbuch als PDF herunterladen"}
        </a>
      </Button>

      {info && (
        <p className="inline-flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
          <Info className="h-3.5 w-3.5" aria-hidden="true" />
          <span>
            Version <strong className="text-foreground">{info.version}</strong>
          </span>
          <span aria-hidden="true">·</span>
          <span>
            Zuletzt aktualisiert{" "}
            <time dateTime={info.generatedAt} className="text-foreground">
              {formatDate(info.generatedAt)}
            </time>
          </span>
          <span aria-hidden="true">·</span>
          <span>{formatSize(info.sizeBytes)}</span>
          <span aria-hidden="true">·</span>
          <span title="Hash über den Seiteninhalt">
            Inhalt&nbsp;
            <code className="font-mono text-foreground/80">{info.contentHash}</code>
          </span>
        </p>
      )}

      {usingFallback && (
        <p className="text-xs text-destructive">
          ⚠ Aktuelle PDF-Generierung fehlgeschlagen – letzte erfolgreiche
          Version wird angeboten.
        </p>
      )}
    </div>
  );
};

export default HandbuchPdfDownload;
