import { useEffect, useState } from "react";
import { Download, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";

interface HandbuchPdfDownloadProps {
  /** Primary PDF URL (e.g. /downloads/handbuch-boxautomat.pdf) */
  primaryUrl: string;
  /**
   * Optional fallback URL. Defaults to `<primary>.last-good.pdf` derived from
   * the primary path (e.g. handbuch-boxautomat.last-good.pdf).
   */
  fallbackUrl?: string;
  /** Suggested filename for the download attribute. */
  fileName?: string;
  ariaLabel?: string;
  children?: React.ReactNode;
}

const deriveFallback = (url: string) =>
  url.replace(/\.pdf(\?.*)?$/i, ".last-good.pdf$1");

/**
 * Download button that probes the primary PDF on mount. If the request fails
 * (404, network error, or empty response), it transparently switches to the
 * last-known-good snapshot generated by the build script.
 */
const HandbuchPdfDownload = ({
  primaryUrl,
  fallbackUrl,
  fileName,
  ariaLabel,
  children,
}: HandbuchPdfDownloadProps) => {
  const fallback = fallbackUrl ?? deriveFallback(primaryUrl);
  const [resolvedUrl, setResolvedUrl] = useState(primaryUrl);
  const [usingFallback, setUsingFallback] = useState(false);
  const [unavailable, setUnavailable] = useState(false);

  useEffect(() => {
    let cancelled = false;

    const probe = async (url: string) => {
      try {
        const res = await fetch(url, { method: "HEAD", cache: "no-store" });
        if (!res.ok) return false;
        const len = res.headers.get("content-length");
        if (len !== null && Number(len) === 0) return false;
        return true;
      } catch {
        return false;
      }
    };

    (async () => {
      if (await probe(primaryUrl)) {
        if (!cancelled) {
          setResolvedUrl(primaryUrl);
          setUsingFallback(false);
        }
        return;
      }
      if (await probe(fallback)) {
        if (!cancelled) {
          setResolvedUrl(fallback);
          setUsingFallback(true);
        }
        return;
      }
      if (!cancelled) setUnavailable(true);
    })();

    return () => {
      cancelled = true;
    };
  }, [primaryUrl, fallback]);

  if (unavailable) {
    return (
      <div
        role="alert"
        className="inline-flex items-center gap-2 rounded-md border border-destructive/40 bg-destructive/10 px-4 py-2 text-sm text-destructive"
      >
        <AlertTriangle className="h-4 w-4" />
        PDF aktuell nicht verfügbar – bitte später erneut versuchen.
      </div>
    );
  }

  return (
    <div className="flex flex-col items-start gap-1">
      <Button asChild size="lg" className="gap-2">
        <a
          href={resolvedUrl}
          download={fileName}
          aria-label={ariaLabel}
        >
          <Download className="h-5 w-5" />
          {children ?? "Handbuch als PDF herunterladen"}
        </a>
      </Button>
      {usingFallback && (
        <p className="text-xs text-muted-foreground">
          ⚠ Aktuelle PDF-Generierung fehlgeschlagen – letzte erfolgreiche
          Version wird angeboten.
        </p>
      )}
    </div>
  );
};

export default HandbuchPdfDownload;
