ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS gtin text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mpn text NOT NULL DEFAULT '';

ALTER TABLE public.product_variants
  ADD COLUMN IF NOT EXISTS gtin text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mpn text NOT NULL DEFAULT '';